### ISSUE TITLE
How to make it work like Shopify?

### ISSUE THREAD

**Issue by alexlii1971** [winnipress/winnipress#1]
Hello,

There were lots of Wordpress forks, but no one actually creative.

On Shopify, an shop owner can upload and see only the plugin and themes that belongs them, and mapping a custom domain.

Is it possible to achieve that on Wordpress or Winnipress?

**Comment by winnipress** [comment]
May you list all the WordPress forks you know?

Anyways, I don't think WordPress or its forks are intended to be creative. They are just a toolset to make creative things happen. You would have to be the creative one, in any case.

The model you propose, in which plugins and themes are indepentent for each user could fit in the WordPress Multisite version. I took the multisite feature out for WinniPress because it does not fit the WinniPress goals.

I wait for your list of WordPress forks and yeah, you should start your own fork too and make your dreams come true. You can name it something like ShopiPress.
